"""add language to documents

Revision ID: 82ddcfe18338
Revises: 21298ceddbdf
Create Date: 2026-07-11 17:33:55.119818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ddcfe18338'
down_revision: Union[str, Sequence[str], None] = '21298ceddbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('language', sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'language')
    # ### end Alembic commands ###
