"""add idp identity columns to users

Revision ID: ef22d12e25af
Revises: 82ddcfe18338
Create Date: 2026-07-12 17:13:16.663063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef22d12e25af'
down_revision: Union[str, Sequence[str], None] = '82ddcfe18338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('issuer', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_user_issuer_subject', 'users', ['issuer', 'subject'])
    op.create_unique_constraint('uq_user_email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email', 'users', type_='unique')
    op.drop_constraint('uq_user_issuer_subject', 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('users', 'subject')
    op.drop_column('users', 'issuer')
    # ### end Alembic commands ###
